:tip-caption: ðŸ’¡
:note-caption: ðŸ“
:caution-caption: âš ï¸
:warning-caption: ðŸ”¥
:important-caption: â—ï¸

= What is the Shell?
:toc: left
:experimental:
:commandkey: &#8984;
:optionkey: &#8997;
:shiftkey: &#x21e7;
:ext-relative: adoc
:imagesdir: ./images

Inspired by the original UNIX operating system, *the trademark feature of all UNIX-like operating systems is the shell*. Common Unix-like operating systems include macOS and any distribution of Linux. Check out this awesome video to learn more about the original UNIX shell: 

video::tc4ROCJYbm0[youtube, width=600, height=400, align=center]


== Files and Processes

Everything in a Unix-like operating system is a *file*. A speical type of files called *executable files* become *processes*. Processes occur anytime we run a program by executing an *executable file*. 


|===
|*EXECUTABLE files (become processes)*|*NON EXECUTABLE files (rely on processes)*
|

Type of file that runs a program when it's opened by executing a set of instructions (a.k.a. do stuff like listen to songs, watch videos or view images) based on compiled programs/scripts

Common examples: Spotify, Web Browsers (Safari, Firefox, Chrome), Microsoft Word/PowerPoint/Excel, *commands*

Common file extensions: .APP .EXE .SRC .VB|

Type of file that relies on executable files to be of any use 

Common examples: audio files, compressed files, data files, system files, Word/PowerPoint/Excel files

Common file extensions: .mp3, .mpg, .jpg, .png, .doc, .ppt, .xsl, .tar, .log )
|===



== Running a Shell Process in the Terminal



=== What's the difference between the terminal and the shell?

If you're a bit confused about the difference between the shell and the terminal check out the video below (but don't worry, this confusion will fade away as you gain more experience with running commands). 


video::Yt57-gg9jVg[youtube, width=600, height=400, align=center]

=== How do I open/quit the terminal?

*Opening the Terminal*

For macOS, do one of the following:


. Spotlight Search:
+
* Press kbd:[ {commandkey} + space] and type `terminal` in the Spotlight Search box. 
+
. Finder:
+
* open the /Applications/Utilities folder, then double-click Terminal.
+
. Launchpad
+
* Click the Launchpad icon in the Dock, type Terminal  in the search fields, then click Terminal.


For Windows, do one of the following: +

. Start Menu Search (Windows 10):
+
* Press kbd:[WIN] and type either `cmd` or `PowerShell`. Click Command Prompt or PowerShell.

. Run Menu:
+
* Press kbd:[WIN + R] to open the Run menu. Type `cmd` or `PowerShell` and hit enter.

__(PowerShell is generally recommended over Command Prompt as both can run CMD commands, but PowerShell has access to more Unix-like commands. Please also note that Windows commands may differ from Unix-based commands. We recommend downloading the Ubuntu WSL, available for free in the Microsoft Store on Windows 10, to follow most tutorials.)__

*Quitting the Terminal*


For macOS: 

. In the Menu Bar, click Terminal > Quit Terminal.

=== What are commands?

*Commands* are shell executables that tell your computer to perform certain types of tasks. All commands can be run in the command line. Some examples of things that commands can do are creating or removing files, moving a directory, or running another executable. Other commands may download, compile, and install a program. Generally, commands won't be able to directly interact with a GUI (graphical user interface).


* syntax (commands, options, arguments)

In general, a command will have a syntax something like: +
`command -arguments target`. +
It is possible to use many terms at once:
`sudo apt-get install -V -m --yes --no-download g++` +
Or to have a very short, one-term command:
`ls`.


=== How do I run commands?

Once you are in the terminal, running commands is usually quite straightforward.
Unlike trying to perform actions outside the terminal, such as downloading and running an installer or updating a program, there is very little overhead.

In the command line, type your command and press enter, and it will try to run. +
As an example, type `apt-get update` -- this command should update any applications that have been installed using `apt-get install`.

Did you get a `Permission denied` message? Let's try again with a slight modification: `sudo apt-get update`. This gives the command elevated priveleges, letting it get around some of the permission errors you'll encounter. Make sure that you know what commands do before you run them with `sudo` -- these permissions are often restricted for a reason!

If `sudo` isn't working for you, you'll need to be added to the sudo group on your computer.  If you're on Windows, the equivalent to using `sudo` is to run CMD or PowerShell as an administrator (right click and select `Run as Administrator`).



=== How to Use the Terminal (Like a Pro)


The following video contains key information about shell features including:

* command line prompt
* auto-complete
* history (arrow up)
* keyboard shortcuts
* wildcards
* piping
* case sensitivity

.8 Shell Shortcuts Every User Should Know
video::C-AQAJXdoS8[youtube,width=600,height=400,align=center]


=== The command prompt

When you first login to the terminal, your current working directory will likely be your home directory. You can tell which directory you're in based on the prompt. The prompt tells you which user account you're using, what computer you're logged into as well as your current working directory. 

For example, my prompt appears like this:

[source,sh]
[subs=+quotes]
----
Dylans-Macbook-Pro:~ eljefe$ 
----
Dylas-Macbook-Pro is my computer, the tilde (~) means that I'm in my home directory and in the dollar sign ($) indicates that I don't have administrative access (more on that later).