= Understanding Commands
:toc: left

So far we've covered:

. navigate 
. inspect
. alter
. pwd cd ls file mkdir rm rmdir...

However we've only scratched the surface. In this module you will learn how find help to run commands successfully. 

* `*type*` - Display information about command type
* `*which*` - Locate a command
* `*help*` - Display reference page for shell builtin
* `*man*` - Display an online command reference

== Identifying Commands

In the command-line, list all of the aviailable commands by double tapping the "tab" key:

```sh
Dylans-MacBook-Pro-5:~ eljefe$ 
Display all 1424 possibilities? (y or n)
!
```
In the example above, I was asked if I'd like to display all 1424 possible commands! We've covered less than 10. With so many commands, how can we break them down to develop a better understanding?


There are 4 types of commands:

. Executable Programs
. Builtin Commands
. Shell Functions
. Aliases

=== type 

`*type*` command displays the kind of command that the shell will execute.

```sh
Dylans-MacBook-Pro-5:doc-linux-connected eljefe$ type cp
cp is /bin/cp

Dylans-MacBook-Pro-5:doc-linux-connected eljefe$ type cd
cd is a shell builtin

Dylans-MacBook-Pro-5:doc-linux-connected eljefe$ type ls
ls is hashed (/bin/ls)
```

=== which

`*which*`command determines the exact location of an executable program. 

```sh
Dylans-MacBook-Pro-5:doc-linux-connected eljefe$ which ls
/bin/ls
eljefe
```
== Getting Help

Now that you know how to identify the four kinds of commands, let's shift our attention to getting help. 

=== help

Access documentation for builtin shell commands with the `*help*`
command. 

```sh
Dylans-MacBook-Pro-5:doc-linux-connected eljefe$ help cd
cd: cd [-L|-P] [dir]
    Change the current directory to DIR.  The variable $HOME is the
    default DIR.  The variable CDPATH defines the search path for
    the directory containing DIR.  Alternative directory names in CDPATH
    are separated by a colon (:).  A null directory name is the same as
    the current directory, i.e. `.'.  If DIR begins with a slash (/),
    then CDPATH is not used.  If the directory is not found, and the
    shell option `cdable_vars' is set, then try the word as a variable
    name.  If that variable has a value, then cd to the value of that
    variable.  The -P option says to use the physical directory structure
    instead of following symbolic links; the -L option forces symbolic links
    to be followed.
```

Dylans-MacBook-Pro-5:doc-linux-connected eljefe$ ```

NOTE: when square brackets appear in the description of a command's syntax, they indicate optional items. A vertical bar indicates mutally exclusive items.

In the case of the cd command above, 

`cd [-L|-P`] [dir]`

means that the `*cd*` command may be followed by either a -L or -P. It also means that specifying a directory is optional. 

= man

`*man*`(short for _manual_ or _man page_) gives you access to documentation (usually with the prgram `*less*`) for many of the executable programs stored int the /bin directory. 

```sh 
man mkdir
```
Man pages contain:

Man pages have a general standard format with:

* *NAME*
** `*command name*` - basic description

* *SYNOPSIS*
** `*command name*` [`*options*`] (underlinged) required_input ...

* *DESCRIPTION*
** in-dpeth description

(and the list goes on)

NOTE: man pages do not give examples, they are intended for solely for reference. 

On most Linux systems, man uses less to display the manual page, so all of the familiar less commands work while displaying the page.


== README and other Documentation Files

Software packages installed on system have documentation files in /usr/share/doc directory. Text files can be viewed with*`*less*` and HTML files can be viewed with web browser.


== Manually installing programs


In unix, the majority of programs that you install are distributed as "source code" (text files. 

There's no install button like other apps. But since the source-code was writen by a developer in text format, we have to convert it to a language that the computer can understand: binary. This is called _compiling_ (turning human readable code into computer machine code). 

this means that when you download them, you usually have to install them with the command line. 

Compiling from the source code is a standard procedure for 90% of programs. We’ll demonstrate by installing the command units, a program for converting between units of measurement in our home directory.

First we'll get the source code. 

wget is a program for downloading files from the internet

curl is a program for downloading files from the internet (for mac)

Notice the file ends with tar.gz - this means that it is a tar archive compressed with *gzip*

for linux:

```sh
$ wget -O https://ftp.gnu.org/gnu/units/units-2.19.tar.gz
```
for mac

```sh
$ curl -O https://ftp.gnu.org/gnu/units/units-2.19.tar.gz
```

```sh
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:-- 78 1241k   78  976k    0     0  1046k      0  0:00:01 --:--100 1241k  100 1241k    0     0  1206k      0  0:00:01  0:00:01 --:--:-- 1206k
  
```

the file is compressed, lets expand themL: 

```sh
$ ls units-2.19.tar.gz 
units-2.19.tar.gz
```

```sh
$ tar xzvf units-2.19.tar.gz 
x units-2.19/
x units-2.19/units.man
x units-2.19/icon_ms.png
x units-2.19/README.OS2
x units-2.19/Makefile.OS2
x units-2.19/Makefile.in
x units-2.19/parse.y
x units-2.19/getopt1.c
x units-2.19/units.texinfo
x units-2.19/parse.tab.c
x units-2.19/strfunc.c
x units-2.19/UnitsWin.texinfo
x units-2.19/Makefile.Win
x units-2.19/units.h
x units-2.19/getopt.h
x units-2.19/units.txt
x units-2.19/install-sh
x units-2.19/units.c
x units-2.19/ChangeLog
x units-2.19/configure
x units-2.19/UnitsMKS.pdf
x units-2.19/winmkdirs.bat
x units-2.19/UnitsWin.pdf
x units-2.19/NEWS
x units-2.19/definitions.units
x units-2.19/getopt.c
x units-2.19/units.info
x units-2.19/texi2man
x units-2.19/makeobjs.cmd
x units-2.19/currency.units
x units-2.19/units_cur
x units-2.19/unitsfile.ico
x units-2.19/unitsprog.ico
x units-2.19/units.dvi
x units-2.19/units.pdf
x units-2.19/configure.ac
x units-2.19/INSTALL
x units-2.19/UnitsMKS.texinfo
x units-2.19/locale_map.txt
x units-2.19/README
x units-2.19/setvcvars.sh
x units-2.19/fdl-1.3.texi
x units-2.19/COPYING
x units-2.19/units.rc
```

There will newarly always be a README file. This file creates instrucitons on how to install. 

Normally programs are installed using three commands:

`*.configure*` 
`*make*`
`*make install*`

First stage is to configure the compiling process using a script that is supplied with the source code
- this checks that the machine has the required dependencies, enables and disables features; and sets options. Try it:

```sh
$./configure --prefix=$HOME/install
```

NOTE: we add one option (--prefix=$HOME/install) - we tell the system to install units in the install directory of our home directory. We would not have permission to install it to the default location

continuing:

```sh
$ make
$ sudo make install
password:
$ cd
```
The package is installed. 

TIP: always good practice to install all your local programs that are utilities to one place so you can just add this location to your "PATH" and your computer will know where to ook for the programs.

Expore the install directory (Linux)
```sh
cd 
ls install
ls intall/bin
```
mac:

```sh
$ which units
$ ls /usr/local/bin/units
$ type units
units is hashed (/usr/local/bin/units)
```

we can add this to the path by executing 

```sh
$ export PATH=$PATH:$HOME/install/bin
```
Try it out. If you have ft/s, how many inches/day? 

```sh
$ units
```
press control-D or control-C to exit. 





== Errors

=== Readme and other doc files





```sh
Dylans-MacBook-Pro-5:units-2.19 eljefe$ make
gcc -DUNITSFILE=\"/usr/local/share/units/definitions.units\" -DLOCALEMAP=\"/usr/local/share/units/locale_map.txt\" -DSUPPORT_UTF8 -DPACKAGE_NAME=\"GNU\ units\" -DPACKAGE_TARNAME=\"units\" -DPACKAGE_VERSION=\"2.19\" -DPACKAGE_STRING=\"GNU\ units\ 2.19\" -DPACKAGE_BUGREPORT=\"adrianm@gnu.org\" -DPACKAGE_URL=\"http://www.gnu.org/software/units/\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I/opt/local/include -g -O2 -fpic -I. -c units.c
gcc -DUNITSFILE=\"/usr/local/share/units/definitions.units\" -DLOCALEMAP=\"/usr/local/share/units/locale_map.txt\" -DSUPPORT_UTF8 -DPACKAGE_NAME=\"GNU\ units\" -DPACKAGE_TARNAME=\"units\" -DPACKAGE_VERSION=\"2.19\" -DPACKAGE_STRING=\"GNU\ units\ 2.19\" -DPACKAGE_BUGREPORT=\"adrianm@gnu.org\" -DPACKAGE_URL=\"http://www.gnu.org/software/units/\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I/opt/local/include -g -O2 -fpic -I. -c parse.tab.c
gcc -DUNITSFILE=\"/usr/local/share/units/definitions.units\" -DLOCALEMAP=\"/usr/local/share/units/locale_map.txt\" -DSUPPORT_UTF8 -DPACKAGE_NAME=\"GNU\ units\" -DPACKAGE_TARNAME=\"units\" -DPACKAGE_VERSION=\"2.19\" -DPACKAGE_STRING=\"GNU\ units\ 2.19\" -DPACKAGE_BUGREPORT=\"adrianm@gnu.org\" -DPACKAGE_URL=\"http://www.gnu.org/software/units/\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I/opt/local/include -g -O2 -fpic -I. -c getopt.c
getopt.c:541:6: warning: add
      explicit braces to avoid
      dangling else
      [-Wdangling-else]
                   else
                   ^
1 warning generated.
gcc -DUNITSFILE=\"/usr/local/share/units/definitions.units\" -DLOCALEMAP=\"/usr/local/share/units/locale_map.txt\" -DSUPPORT_UTF8 -DPACKAGE_NAME=\"GNU\ units\" -DPACKAGE_TARNAME=\"units\" -DPACKAGE_VERSION=\"2.19\" -DPACKAGE_STRING=\"GNU\ units\ 2.19\" -DPACKAGE_BUGREPORT=\"adrianm@gnu.org\" -DPACKAGE_URL=\"http://www.gnu.org/software/units/\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I/opt/local/include -g -O2 -fpic -I. -c getopt1.c
gcc -g -O2 -fpic -L/opt/local/lib  -o units units.o parse.tab.o getopt.o getopt1.o   
ld: warning: directory not found for option '-L/opt/local/lib'
sed s!@DATAFILE@!/usr/local/share/units/definitions.units! ./units.man > units.1
sed -e "s@outfile_name = 'currency.units'@outfile_name='/usr/local/com/units/currency.units'@"\
            -e "s@/usr/bin/python@/usr/bin/python@" \
             ./units_cur > units_cur_inst
Dylans-MacBook-Pro-5:units-2.19 eljefe$ make install
./install-sh -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 644 units.1 /usr/local/share/man/man1/`echo units|sed 's,x,x,'`.1
./install-sh -c -d /usr/local/share/info
/usr/bin/install -c -m 644 units.info /usr/local/share/info
if test -f /usr/local/share/info/dir; then \
       if /bin/sh -c 'install-info --version' >/dev/null 2>&1; then \
         install-info --dir-file=/usr/local/share/info/dir \
                    /usr/local/share/info/units.info; \
       else true; fi \
     else true; fi
Trying to update currency.units (will use existing file if this fails)
./units_cur currency.units
Traceback (most recent call last):
  File "./units_cur", line 57, in <module>
    import requests
ImportError: No module named requests
make: [currency-units-update] Error 1 (ignored)
if [ ! -s currency.units ]; then cp ./currency.units currency.units;fi
./install-sh -c -d /usr/local/share/units/ /usr/local/bin /usr/local/com/units/
mkdir: /usr/local/com: Permission denied
mkdir: /usr/local/com: No such file or directory
make: *** [install-support] Error 1
Dylans-MacBook-Pro-5:units-2.19 eljefe$ sudo make install
Password:
./install-sh -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 644 units.1 /usr/local/s
hare/man/man1/`echo units|sed 's,x,x,'`.1
./install-sh -c -d /usr/local/share/info
/usr/bin/install -c -m 644 units.info /usr/loca
l/share/info
if test -f /usr/local/share/info/dir; then \
       if /bin/sh -c 'install-info --version' >
/dev/null 2>&1; then \
         install-info --dir-file=/usr/local/sha
re/info/dir \
                    /usr/local/share/info/units
.info; \
       else true; fi \
     else true; fi
Trying to update currency.units (will use exist
ing file if this fails)
./units_cur currency.units
Traceback (most recent call last):
  File "./units_cur", line 57, in <module>
    import requests
ImportError: No module named requests
make: [currency-units-update] Error 1 (ignored)
if [ ! -s currency.units ]; then cp ./currency.units currency.units;fi
./install-sh -c -d /usr/local/share/units/ /usr/local/bin /usr/local/com/units/
/usr/bin/install -c -m 644 ./definitions.units /usr/local/share/units/definitions.units
rm -f /usr/local/share/units/currency.units
/usr/bin/install -c -m 644 currency.units /usr/local/com/units/currency.units
if [ /usr/local/com/units/ != /usr/local/share/units/ ];then ln -sf /usr/local/com/units/currency.units /usr/local/share/units/currency.units;fi
/usr/bin/install -c -m 644 ./locale_map.txt /usr/local/share/units/locale_map.txt
if test yes = yes; then \
       /usr/bin/install -c units_cur_inst /usr/local/bin/`echo units_cur|sed 's,x,x,'`;fi
if test no = yes; then make install-mks; fi
./install-sh -c -d /usr/local/bin 
/usr/bin/install -c units /usr/local/bin/`echo units|sed 's,x,x,'`
Dylans-MacBook-Pro-5:units-2.19 eljefe$ 
```